
#ifndef GLOBAL_H
#define GLOBAL_H




#define LIGHT_ATTENUATION_CUTOFF 0.01f


// Directories
#define DEFAULT_RESOURCE_DIR "resources/"
#define DEFAULT_IMPORT_DIR "import/"
#define DEFAULT_CORE_DIR "core/"

// Shaders


#define DEFAULT_SPOTLIGHT_SHADOW_W 1024
#define DEFAULT_SPOTLIGHT_SHADOW_H 1024
#define DEFAULT_POINTLIGHT_SHADOW_W 1024
#define DEFAULT_POINTLIGHT_SHADOW_H 1024
#define DEFAULT_DIRLIGHT_SHADOW_W 2048
#define DEFAULT_DIRLIGHT_SHADOW_H 2048

#define DEFAULT_SEL_R 0.0f
#define DEFAULT_SEL_G 1.0f
#define DEFAULT_SEL_B 1.0f
#define DEFAULT_SEL_A 0.5f
#define DEFAULT_SEL_MASK_A 0.2f
#define DEFAULT_RENDER_W 1920
#define DEFAULT_RENDER_H 1080


#define DEFAULT_FB_RES_X 1920
#define DEFAULT_FB_RES_Y 1080

// Material map type
#define TEXMAPTYPES 11

#endif
